version: '3'
services:
  mongo-taskhelper:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<username>
      - MONGO_INITDB_ROOT_PASSWORD=<password>
    volumes:
      - mongodb_taskhelper_data:/data/db
    restart: always

volumes:
  mongodb_taskhelper_data:
